# Generated by Django 4.0.1 on 2022-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Fullname', models.CharField(max_length=70)),
                ('StdiD', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
    ]
