# Generated by Django 4.0.1 on 2022-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Amt',
            field=models.FloatField(null=True),
        ),
    ]
