# Generated by Django 4.0.1 on 2022-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bill_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='media/')),
                ('Fullname', models.CharField(max_length=70)),
                ('Expertise', models.CharField(max_length=70)),
                ('Exp', models.CharField(max_length=70)),
            ],
        ),
    ]
