# Generated by Django 4.0.1 on 2022-03-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
