# Generated by Django 4.0.1 on 2022-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='Section',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
