# Generated by Django 4.0.1 on 2022-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bill_address_bill_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Password',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
