# Generated by Django 4.0.1 on 2022-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_bill_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
