# Generated by Django 4.0.1 on 2022-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Fullname', models.CharField(max_length=70)),
                ('StdiD', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Amt', models.FloatField()),
                ('Section', models.CharField(max_length=6)),
                ('Address', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
