# Generated by Django 4.0.1 on 2022-04-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
