# Generated by Django 4.0.1 on 2022-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_bill_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=70)),
                ('StdiD', models.CharField(max_length=70, unique=True)),
                ('Password', models.SlugField(blank=True)),
                ('Amt', models.FloatField()),
                ('Section', models.CharField(max_length=6)),
                ('Address', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
