# Generated by Django 4.0.1 on 2022-04-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_student_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5')], default='L1', max_length=6),
        ),
    ]
