# Generated by Django 4.0.1 on 2022-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Fathers_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.SlugField(blank=True),
        ),
    ]
